#ifndef settings_h
#define settings_h

#define SERIAL_PORT 9600

#define CHECK_INTERVAL (4 * 60 * 60 * 1000) // 4h

#define LEVEL_WARNING 83 // 0--100

#define DISTANCE_FOR_EMPTY 220
#define DISTANCE_FOR_FULL 70

#define INDICATOR_LED_ERROR_BLINK_INTERVAL 500

#define ULTRASONIC_SAMPLES_INTERVAL 100
#define ULTRASONIC_MAX_SAMPLES 10
#define ULTRASONIC_MAX_TRIES 30
#define ULTRASONIC_TRIM_SAMPLES 3

#endif
