#ifndef settings_h
#define settings_h

#define DEBUG false
#define DEBUG_RXTX false

#define CONSOLE_SERIAL_PORT_BAUD 9600

#define MEASURE_INTERVAL 3600000            // 1h
#define MEASURE_FATAL_RECOVERY_TIMER 300000 // 5 min

#define STARTUP_TIMER_INTERVAL 250

#define LEVEL_MAX_M3 6.0
#define LEVEL_WARNING 83 // 0--100

#define DISTANCE_FOR_EMPTY 182
#define DISTANCE_FOR_FULL 39

#define INDICATOR_LED_BUSY_BLINK_INTERVAL 2000
#define INDICATOR_LED_BUSY_IMPULSE_INTERVAL 40
#define INDICATOR_LED_ERROR_BLINK_INTERVAL 500
#define INDICATOR_LED_ERROR_IMPULSE_INTERVAL 250
#define INDICATOR_METER_MAX_PWM 222 // 0--255

#define ULTRASONIC_SAMPLES_INTERVAL 1000
#define ULTRASONIC_MAX_SAMPLES 10
#define ULTRASONIC_MAX_TRIES 30 // 0--127
#define ULTRASONIC_TRIM_SAMPLES 3

#define TRANSPORT_SERIAL_PORT_BAUD 4800
#define TRANSPORT_TIMEOUT_EXECUTION 120000
#define TRANSPORT_TIMEOUT_RESPONSE 60000

#define UI_ERROR_AUTOHIDE_DELAY 60000

#define REMOTE_CONTROL_INIT_DELAY 180000 // 3 min
#define REMOTE_CONTROL_INTERVAL 600000   // 10 min

#if __has_include("settings.local.h")
#include "settings.local.h"
#endif
#endif
