#ifndef settings_h
#define settings_h

#define DEBUG false
#define DEBUG_RXTX false
#define SERIAL_PORT 9600

#define CHECK_INITIAL_DELAY 60000 // 1 min
#define CHECK_INTERVAL 14400000   // 4h
#define STARTUP_TIMER_INTERVAL 500

#define LEVEL_WARNING 83 // 0--100

#define DISTANCE_FOR_EMPTY 220
#define DISTANCE_FOR_FULL 70

#define INDICATOR_LED_INFO_BLINK_INTERVAL 1000
#define INDICATOR_LED_INFO_IMPULSE_INTERVAL 50
#define INDICATOR_LED_ERROR_BLINK_INTERVAL 500
#define INDICATOR_LED_ERROR_IMPULSE_INTERVAL 250
#define INDICATOR_METER_MAX_PWM 222 // 0--255

#define ULTRASONIC_SAMPLES_INTERVAL 100
#define ULTRASONIC_MAX_SAMPLES 10
#define ULTRASONIC_MAX_TRIES 30
#define ULTRASONIC_TRIM_SAMPLES 3

#define TRANSPORT_TIMEOUT_EXECUTION 120000
#define TRANSPORT_TIMEOUT_RESPONSE 60000

#if __has_include("settings.local.h")
#include "settings.local.h"
#endif
#endif
